### ISSUE TITLE
Article details tpl may display double ORCID icon

### ISSUE THREAD

**Issue by jmacgreg** [pkp/classic#82]
**Describe the bug**
If an author authenticates their ORCID iD against a submission, the ORCID iD icon should display next to their name. But in this case, it will display twice. 

**To Reproduce**
- Enable ORCID plugin
- ask an author to authenticate their ORCID iD
- publish the article

**Screenshots**

<img width="329" alt="image" src="https://user-images.githubusercontent.com/201446/86424818-8aac4380-bcb1-11ea-87b5-1cfc32fbf360.png">

**Versions**
- OJS 3.1.2-2. 
- Classic theme 1.0.1.0. 

**Solution**
Edit line 87 of `templates/frontend/objects/article_details.tpl`, change: 

`<a class="orcid-image-url" href="{$author->getOrcid()}"><img src="{$baseUrl}/{$orcidImageUrl}"></a>`

... to: 

`<a class="orcid-image-url" href="{$author->getOrcid()}"></a>`

The ORCID plugin javascript will use the class name to add an ORCID button via CSS/SVG. I am not sure if this is the "correct" way to do this or not, but it worked. I am also not sure if this is present in other themes.

**Comment by NateWr** [comment]
I'd recommend that the ORCID plugin not try to do that with JavaScript. It will:

- Be brittle and prone to errors because theme developers don't know this is a special CSS class. (A refactor by a new dev in one year will reintroduce this bug.)
- Make an additional server request for a tiny JS file, which will delay time to first paint.
- Create "layout jank" where the page layout shifts abruptly after it is rendered.

If the ORCID plugin wants to make it easy to support the display, it could do so by providing a full URL to the ORCID SVG file to each template where it is needed. But the decision of what, where and how to display the relationship should be up to the theme.

**Comment by jmacgreg** [comment]
Thanks @NateWr! I'll review this with the ORCID crew.

**Comment by jmacgreg** [comment]
From the ORCID devs: 

"The approach suggested in https://github.com/pkp/classic/issues/82#issuecomment-654168329 is definitely a better approach vs using JS. 
I’m not sure whether "full URL to the ORCID SVG file” means a link to a copy of the iD icon included in the plugin files or a link to the asset on our site, however, I suggest that include a local copy of the iD icon and not link to files on our site as locations are subject to change without notice. iD icon files can be downloaded from https://orcid.figshare.com/articles/ORCID_iD_icon_graphics/5008697"

**Comment by NateWr** [comment]
The full link to the icon would refer to the `svg` file in the orcid plugin, at `templates/images/orcid.svg`.

Should we migrate this issue to the orcid plugin repository?

**Comment by jmacgreg** [comment]
Done!
